"""Helper functions for writing VASP input and reading VASP output.

This module contains the file-level plumbing for the VASP interface:
writers for the POSCAR, INCAR, KPOINTS, and POTCAR files, and a parser
for the ``vasprun.xml`` file produced by a completed calculation.
"""
from __future__ import annotations

__all__ = [
    "group_species",
    "write_poscar",
    "write_incar",
    "write_kpoints",
    "write_potcar",
    "write_mm_charges",
    "write_pme_data",
    "read_mm_forces",
    "read_vasprun",
    "run_vasp",
    "VaspExecutionError",
]

import gzip
import os
import shutil
import subprocess
import xml.etree.ElementTree as ET
from typing import TYPE_CHECKING

import numpy as np

from pydft_qmmm.embedding.pme_grid import write_pme_data

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping, Sequence
    from typing import Any
    from numpy.typing import NDArray


class VaspExecutionError(RuntimeError):
    """An exception raised when a VASP calculation fails.

    Args:
        directory: The working directory of the failed calculation.
        message: A description of the failure.
    """

    def __init__(self, directory: str, message: str) -> None:
        super().__init__(
            f"VASP calculation in '{directory}' failed: {message}\n"
            "Inspect the OUTCAR, stdout, and stderr files in that "
            "directory for details.",
        )


def group_species(
        symbols: Sequence[str],
) -> tuple[list[str], list[int], list[int]]:
    """Group atoms by chemical species for the POSCAR.

    Args:
        symbols: The element symbol of each atom, in system order.

    Returns:
        The distinct species in order of first appearance, the number of
        atoms of each species, and the permutation ``order`` such that
        ``[symbols[i] for i in order]`` is grouped by species.  A force
        array in POSCAR order is mapped back to the input order by
        indexing with the inverse of ``order``.
    """
    species: list[str] = []
    for symbol in symbols:
        if symbol not in species:
            species.append(symbol)
    order: list[int] = []
    counts: list[int] = []
    for symbol in species:
        indices = [i for i, s in enumerate(symbols) if s == symbol]
        order.extend(indices)
        counts.append(len(indices))
    return species, counts, order


def write_poscar(
        path: str,
        symbols: Sequence[str],
        positions: NDArray[np.float64],
        cell: NDArray[np.float64],
        comment: str = "Generated by PyDFT-QMMM",
) -> tuple[list[str], list[int], list[int]]:
    r"""Write a POSCAR file with Cartesian coordinates.

    Args:
        path: The path of the POSCAR file to write.
        symbols: The element symbol of each atom, in system order.
        positions: An Nx3 array of atom positions
            (:math:`\mathrm{\mathring{A}}`), in system order.
        cell: A 3x3 array of lattice vectors
            (:math:`\mathrm{\mathring{A}}`) stored as *rows*.
        comment: The comment placed on the first line of the POSCAR.

    Returns:
        The species, counts, and ordering permutation produced by
        :func:`group_species`, which the caller needs in order to build
        a matching POTCAR and to unscramble the resulting forces.
    """
    species, counts, order = group_species(symbols)
    lines = [comment, "1.0"]
    for vector in cell:
        lines.append(
            "  {:21.16f} {:21.16f} {:21.16f}".format(*vector),
        )
    lines.append("  " + "  ".join(species))
    lines.append("  " + "  ".join(str(count) for count in counts))
    lines.append("Cartesian")
    for i in order:
        lines.append(
            "  {:21.16f} {:21.16f} {:21.16f}".format(*positions[i]),
        )
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return species, counts, order


def _format_incar_value(value: Any) -> str:
    """Render a Python value using VASP's INCAR conventions.

    Args:
        value: The value to render.

    Returns:
        The INCAR representation of the value.
    """
    if isinstance(value, bool):
        return ".TRUE." if value else ".FALSE."
    if isinstance(value, (list, tuple, np.ndarray)):
        return " ".join(_format_incar_value(item) for item in value)
    return str(value)


def write_incar(path: str, tags: Mapping[str, Any]) -> None:
    """Write an INCAR file.

    Args:
        path: The path of the INCAR file to write.
        tags: The INCAR tags and their values.  Booleans are rendered as
            ``.TRUE.``/``.FALSE.`` and sequences are space-joined.  Tag
            names containing a slash, such as
            ``PLUGINS/LOCAL_POTENTIAL``, are written verbatim.
    """
    lines = [
        f"{key} = {_format_incar_value(value)}"
        for key, value in tags.items()
        if value is not None
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def write_kpoints(path: str, kpts: Sequence[int]) -> None:
    """Write a KPOINTS file specifying a Gamma-centered mesh.

    Args:
        path: The path of the KPOINTS file to write.
        kpts: The number of k-points along each reciprocal lattice
            vector.  ``(1, 1, 1)`` selects the Gamma point alone.
    """
    lines = [
        "Generated by PyDFT-QMMM",
        "0",
        "Gamma",
        " ".join(str(int(k)) for k in kpts),
        "0 0 0",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _find_potcar(library: str, name: str) -> str:
    """Locate the POTCAR file for a single species.

    Args:
        library: The directory containing per-species subdirectories.
        name: The name of the species subdirectory, e.g. ``"O"`` or
            ``"Li_sv"``.

    Returns:
        The path of the POTCAR file, which may be gzipped.
    """
    base = os.path.join(library, name, "POTCAR")
    for candidate in (base, base + ".gz", base + ".Z"):
        if os.path.isfile(candidate):
            return candidate
    raise FileNotFoundError(
        f"No POTCAR found for species '{name}' in '{library}'.  Expected "
        f"'{base}' (optionally gzipped).  Check the pp_path keyword or "
        "the VASP_PP_PATH environment variable, and use potcar_map to "
        "select a non-default potential, e.g. potcar_map={'Li': 'Li_sv'}.",
    )


def write_potcar(
        path: str,
        species: Iterable[str],
        library: str,
        potcar_map: Mapping[str, str] | None = None,
) -> None:
    """Write a POTCAR by concatenating per-species potentials.

    Args:
        path: The path of the POTCAR file to write.
        species: The distinct species, in the same order as they appear
            in the POSCAR.
        library: The directory containing per-species subdirectories,
            e.g. ``.../pseudopotential/potpaw_PBE.54``.
        potcar_map: An optional mapping from element symbol to the name
            of the species subdirectory, used to select non-default
            potentials such as ``Li_sv`` for lithium.
    """
    potcar_map = {} if potcar_map is None else potcar_map
    with open(path, "wb") as out:
        for symbol in species:
            source = _find_potcar(library, potcar_map.get(symbol, symbol))
            opener = gzip.open if source.endswith(".gz") else open
            with opener(source, "rb") as fh:  # type: ignore[operator]
                shutil.copyfileobj(fh, out)


def write_mm_charges(
        path: str,
        positions: NDArray[np.float64],
        charges: NDArray[np.float64],
        step: int,
        sigma: float,
) -> None:
    r"""Write MM point charges for the VASP plugin to read.

    This is the contract between two processes: PyDFT-QMMM writes the
    file, and the Python interpreter embedded in VASP reads it.

    Args:
        path: The destination file.
        positions: An Nx3 array of positions
            (:math:`\mathrm{\mathring{A}}`).
        charges: An N array of charges (:math:`e`).
        step: A monotonically increasing stamp, so the plugin can detect
            a stale file left over from a previous evaluation.
        sigma: The Gaussian width (:math:`\mathrm{\mathring{A}}`) used
            to represent the point charges on VASP's FFT grid.  It
            travels with the charges because the plugin runs in a
            separate process and cannot read the interface's settings.
    """
    positions = np.asarray(positions, dtype=np.float64).reshape(-1, 3)
    charges = np.asarray(charges, dtype=np.float64).reshape(-1)
    if len(positions) != len(charges):
        raise ValueError(
            f"{len(positions)} positions but {len(charges)} charges.",
        )
    with open(path, "w") as fh:
        fh.write(f"{len(charges)} {step} {sigma:.12e}\n")
        for (x, y, z), q in zip(positions, charges):
            fh.write(f"{x:.12e} {y:.12e} {z:.12e} {q:.12e}\n")


def read_mm_forces(
        path: str,
        expect_step: int | None = None,
) -> tuple[NDArray[np.float64], int]:
    r"""Read the MM forces the plugin computed.

    Args:
        path: The file to read.
        expect_step: If given, the step stamp the file must carry.

    Returns:
        An Nx3 array of forces
        (:math:`\mathrm{kJ\;mol^{-1}\;\mathring{A}^{-1}}`) and the step.
    """
    with open(path) as fh:
        count, step = fh.readline().split()
        count, step = int(count), int(step)
        if count == 0:
            return np.zeros((0, 3)), step
        data = np.loadtxt(fh, dtype=np.float64, ndmin=2)
    if len(data) != count:
        raise ValueError(
            f"{path} declares {count} forces but holds {len(data)}.",
        )
    if expect_step is not None and step != expect_step:
        raise ValueError(
            f"{path} is at step {step}, expected {expect_step}.",
        )
    return data.copy(), step


def read_vasprun(
        path: str,
) -> tuple[float, NDArray[np.float64]]:
    r"""Read the energy and forces from the last step of a vasprun.xml.

    The free energy ``e_fr_energy`` is returned rather than the energy
    extrapolated to zero smearing, because it is the quantity whose
    gradient VASP reports as the forces.  Using the extrapolated energy
    would make energies and forces mutually inconsistent whenever a
    finite SIGMA is in use.

    Args:
        path: The path of the vasprun.xml file.

    Returns:
        The free energy (:math:`\mathrm{eV}`) and an Nx3 array of forces
        (:math:`\mathrm{eV\;\mathring{A}^{-1}}`), in POSCAR order.
    """
    root = ET.parse(path).getroot()
    calculations = root.findall("calculation")
    if not calculations:
        raise VaspExecutionError(
            os.path.dirname(path) or ".",
            "vasprun.xml contains no completed calculation.",
        )
    calculation = calculations[-1]
    energy_node = calculation.find("energy")
    energy = None
    if energy_node is not None:
        for item in energy_node.findall("i"):
            if item.get("name") == "e_fr_energy" and item.text:
                energy = float(item.text)
    if energy is None:
        raise VaspExecutionError(
            os.path.dirname(path) or ".",
            "vasprun.xml contains no free energy for the final step.",
        )
    forces = None
    for varray in calculation.findall("varray"):
        if varray.get("name") == "forces":
            forces = np.array(
                [
                    [float(x) for x in vector.text.split()]
                    for vector in varray.findall("v")
                    if vector.text
                ],
            )
    if forces is None:
        raise VaspExecutionError(
            os.path.dirname(path) or ".",
            "vasprun.xml contains no forces for the final step.  Ensure "
            "the calculation was not run with NSW>0 and IBRION=-1 "
            "suppressing force evaluation.",
        )
    return energy, forces


def run_vasp(
        command: str,
        directory: str,
        env: dict[str, str] | None = None,
) -> None:
    """Run VASP in the given directory.

    Args:
        command: The shell command that launches VASP, e.g.
            ``"srun vasp_std"``.
        directory: The working directory of the calculation.
    """
    with open(os.path.join(directory, "vasp.out"), "w") as out, \
            open(os.path.join(directory, "vasp.err"), "w") as err:
        process = subprocess.run(
            command,
            shell=True,
            cwd=directory,
            stdout=out,
            stderr=err,
        )
    if process.returncode != 0:
        raise VaspExecutionError(
            directory,
            f"the command '{command}' exited with code "
            f"{process.returncode}.",
        )
